version: '2.4'
services:
  uaa:
    image: mariobros/uaa:0.0.3-SNAPSHOT
    restart: always
    ports:
      - 8090:8090

  redis:
    image: redis:5-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 16379:8081
    depends_on:
      - redis

  eureka-discovery-service:
    image: mariobros/eureka-discovery-service:0.0.3-SNAPSHOT
    restart: always
    ports:
      - 8761:8761

  config-server:
    environment:
      EUREKA_DISCOVERY_SERVICE_HOSTNAME: ${EUREKA_DISCOVERY_SERVICE_HOSTNAME}
    image: mariobros/config-server:0.0.3-SNAPSHOT
    restart: always
    depends_on:
      eureka-discovery-service:
        condition: service_healthy
    ports:
      - 8888:8888

  admin-server:
    environment:
      EUREKA_DISCOVERY_SERVICE_HOSTNAME: ${EUREKA_DISCOVERY_SERVICE_HOSTNAME}
    image: mariobros/admin-server:0.0.3-SNAPSHOT
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 9000:9000

  zuul-gateway-service:
    environment:
      EUREKA_DISCOVERY_SERVICE_HOSTNAME: ${EUREKA_DISCOVERY_SERVICE_HOSTNAME}
    image: mariobros/zuul-gateway-service:0.0.3-SNAPSHOT
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8765:8765

  user-management-service:
    environment:
      EUREKA_DISCOVERY_SERVICE_HOSTNAME: ${EUREKA_DISCOVERY_SERVICE_HOSTNAME}
    image: mariobros/user-management-service:0.0.3-SNAPSHOT
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8080:8080
