server:
  port: 8765

zuul:
  routes:
    uaa:
      path: /uaa/**
      url: http://uaa:8090/uaa
      retryable: true
    user:
      path: /api/user/**
      service-id: user-management-service
      retryable: true
  add-proxy-headers: true
  sensitive-headers:

security:
  oauth2:
    client:
      access-token-uri: http://uaa:8090/uaa/oauth/token
      user-authorization-uri: http://localhost:${server.port}/uaa/oauth/authorize
      client-id: gateway
      client-secret: secret
    resource:
      user-info-uri: http://uaa:8090/uaa/userinfo
      prefer-token-info: false

spring:
  redis:
    host: redis
    port: 6379
    password: strongpass123
  session:
    store-type: redis

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000
  eureka:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
